# Generated by Django 4.2.1 on 2023-05-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('Imagen', models.ImageField(upload_to='imagenes/')),
            ],
        ),
    ]
