# Generated by Django 4.2.1 on 2023-05-27 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Imagenes', '0002_rename_imagen_imagen_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagen',
            old_name='description',
            new_name='descripcion',
        ),
    ]
